default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: fix-and-check
        name: Fix and check (lint, format, type-check)
        entry: make fix-and-check
        language: system
        types: [python]
        pass_filenames: false
      - id: test
        name: Run tests
        entry: uv run tox
        language: system
        types: [python]
        stages: [manual]