name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - uses: astral-sh/setup-uv@v5
      - name: Set up environment
        run: |
          mkdir -p ~/.local/bin
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Download and extract plink
        run: |
          curl -LJO https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20230116.zip
          unzip -n plink_*.zip
          rm plink_*.zip
          chmod +x plink
          ./plink --version
          mv plink ~/.local/bin
          plink --version
      - name: Run tests with Python
        run: |
          pip install tox==4.23.2
          uv run tox -e py
      - name: Generate report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}