name: Coverage
on: [push, pull_request]
jobs:

  coverage:
    name: Coverage
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: Set up environment
        run: |
          mkdir -p ~/.local/bin
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Download and extract plink2
        run: |
          curl -LJO https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20230116.zip
          unzip plink_*.zip
          rm plink_*.zip
          chmod +x plink2
          ./plink --version
          mv plink ~/.local/bin
          plink --version
      - name: Run tests with Python
        run: |
          pip install tox==3.28.0
          pip install poetry==1.4.2
          tox -e py
      - name: Generate report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
