name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up environment
        run: |
          mkdir -p ~/.local/bin
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Download and extract plink
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
            curl -LJO https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20230116.zip
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            curl -LJO https://s3.amazonaws.com/plink1-assets/plink_mac_20230116.zip
          fi
          unzip -n plink_*.zip
          rm plink_*.zip
          chmod +x plink
          ./plink --version
          mv plink ~/.local/bin
          plink --version
      - name: Run tests with Python ${{ matrix.python-version }} on ${{ matrix.os }}
        run: |
          pip install tox==4.23.2
          pip install poetry==1.8.3
          tox -e py